#!/bin/bash
set -e

echo "🔧   Creating DERIVA database roles..."
psql -U postgres <<EOF
  CREATE ROLE deriva; ALTER ROLE deriva WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOBYPASSRLS PASSWORD '${POSTGRES_DERIVA_PASSWORD}';
  CREATE ROLE ermrest; ALTER ROLE ermrest WITH INHERIT NOCREATEROLE CREATEDB LOGIN NOBYPASSRLS PASSWORD '${POSTGRES_ERMREST_PASSWORD}';
  CREATE ROLE hatrac; ALTER ROLE hatrac WITH INHERIT NOCREATEROLE CREATEDB LOGIN NOBYPASSRLS PASSWORD '${POSTGRES_HATRAC_PASSWORD}';
  CREATE ROLE credenza; ALTER ROLE credenza WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOBYPASSRLS PASSWORD '${POSTGRES_CREDENZA_PASSWORD}';
  CREATE ROLE webauthn; ALTER ROLE webauthn WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOBYPASSRLS PASSWORD '${POSTGRES_WEBAUTHN_PASSWORD}';
  GRANT ermrest TO postgres GRANTED BY postgres;
  GRANT hatrac TO postgres GRANTED BY postgres;
  GRANT deriva TO postgres GRANTED BY postgres;
  GRANT webauthn TO postgres GRANTED BY postgres;
  GRANT credenza TO postgres GRANTED BY postgres;
EOF
